---
title: "A3 + R3"
author: "Chang Xu"
output: 
 html_notebook
 pdf_document
---

```{r, include = F}
knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(cache = T)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
options(mc.cores = parallel::detectCores())
library(dplyr)
library(tidyr)
library(ggplot2)
library(anytime)
```


## Load data, split dataset

```{r}
data <- read.csv("../data/ml-latest-small/ratings.csv")
```
```{r}
data$timestamp <- anydate(data$timestamp)
data <- arrange(data, timestamp)
```
```{r}
bins <- as.numeric(max(data$timestamp) - min(data$timestamp))
cut <- seq(0, 1, by=1/30)
quan <- quantile(c(1:bins), cut)
Bin <- rep(NA, nrow(data)-1)
for (i in 1:nrow(data)) {
    dev <- as.numeric(data$timestamp[i] - data$timestamp[1]) + 1
    for (j in 1:30) {
        if (quan[j] <= dev & dev <= quan[j+1]) Bin[i] = j
    }
}
data$Bin <- c(Bin, 30)
```


```{r}
set.seed(0)
## shuffle the row of the entire dataset
data <- data[sample(nrow(data)),]
## get a small dataset that contains all users and all movies
unique.user<-duplicated(data[,1])
unique.movie<-duplicated(data[,2])
index<-unique.user & unique.movie
all.user.movie <- data[!index,]

## split training and test on the rest
rest <- data[index,]
test_idx <- sample(rownames(rest), round(nrow(data)/5, 0))
train_idx <- setdiff(rownames(rest), test_idx)

## combine the training with the previous dataset, which has all users and all movies
data_train <- rbind(all.user.movie, data[train_idx,])
data_test <- data[test_idx,]

## sort the training and testing data by userId then by movieId, 
## so when we update p and q, it is less likely to make mistakes
data_train <- arrange(data_train, userId, movieId)
data_test <- arrange(data_test, userId, movieId)
```
```{r}
U <- length(unique(data$userId))
I <- length(unique(data$movieId))
```

## define RMSE
```{r}
RMSE <- function(rating, est_rating) {
  error <- rep(NA, nrow(rating))
  for (i in 1:nrow(rating)) {
    a <- as.character(rating[i,1])
    b <-as.character(rating[i,2])  
    error[i] <- (rating[i,3]-est_rating[a, b])^2
  }
  return(sqrt(mean(error)))
}

```



## A3 + R3
```{r}
# Alternating least squares
# a function returns a list containing factorized matrices p and q, training and testing RMSEs.

ALS.R3 <- function(f = 10, lambda = 5, max.iter = 5,
            data = data, train = data_train, test = data_test) {

  # Step 1: Initialize Movie matrix (q), User matrix (p), Movie bias(bi) and User bias(bu)
  
  # Step 1: Initialize Movie matrix (q), User matrix (p), Movie bias(bi) and User bias(bu)
  p <- matrix(runif(f*U, -10, 10), ncol = U) 
  colnames(p) <- levels(as.factor(data$userId))
  
  q <- matrix(runif(f*I, -10, 10), ncol = I)
  colnames(q) <- levels(as.factor(data$movieId))
  
  bu <- matrix(rep(0, U), ncol=U)
  colnames(bu) <- levels(as.factor(data$userId))
  
  bi <- matrix(rep(0, I), ncol = I)
  colnames(bi) <- levels(as.factor(data$movieId))
  
  R <- matrix(rep(0, U*I), ncol = I)
  colnames(R) <- levels(as.factor(data$movieId))
  
  bit <- matrix(rep(NA, I*30), ncol = I)
  colnames(bi) <- levels(as.factor(data$movieId))
  
  for (t in 1:30) {
      sub <- filter(train, Bin == t)
      for (i in 1:I) {
        ssub <- filter(sub, movieId == i) 
        r <- sum(ssub$rating)
        n <- length(unique(ssub$userId))+lambda
        bit[t, i] <- r/n
      }
    }
    
   bit_ui <- matrix(rep(0, U*I), ncol = I)
    for (u in 1:U) {
      for (i in 1:I) {
          sub <- filter(train, userId == u, movieId == i)
          if (dim(sub)[1] > 0) {
            t <- as.numeric(sub$Bin)
            bit_ui[u, i] <- bit[t, i]
          }
        }
      }

  #mean of all the ratings in train data set.
  mu <- mean(train$rating)
  
  # sort movie id to make sure that they are from small to large
  movie.id <- sort(unique(data$movieId))
  
  # sort the data by userid then by movie id
  train <- arrange(train, userId, movieId)
  
  
  # set vacant cells to record train and test rmse
  train_RMSE <- c()
  test_RMSE <- c()
  
 for (l in 1:max.iter) {
    # Step 2: Fix q, solve p
    # we need new factors to add bu, bi into calculation
    q_idb <- rbind(rep(1,I), q)
    colnames(q_idb) <- levels(as.factor(data$movieId))
    p_idb <- rbind(bu, p)
    
    for (u in 1:U) {
      # find all the moives rated by user u
      i_ratedby_u <- as.character(train[train$userId==u,]$movieId)
      x<-train[train$userId==u,]$rating
      R_m_u <- matrix(x,ncol=length(x),nrow = 1)
      # update p.tilde
      p_idb[,u] <- solve(q_idb[,i_ratedby_u] %*% t(q_idb[,i_ratedby_u]) + lambda * diag(f+1)) %*%
        q_idb[,i_ratedby_u] %*% t(R_m_u - mu -bi[,i_ratedby_u])
    }
    
    # update bu and p
    bu[1,] <- p_idb[1, ]
    p <- p_idb[-1, ]
    
    # Step 3: Fix p, solve q
    # we need new factors to add bu, bi into calculation
    p.tilde <- rbind(rep(1,U), p)
    colnames(p.tilde) <- levels(as.factor(data$userId))
    q.tilde <- rbind(bi, q)
    
    for (i in 1:I) {
      # find all the users who rate movie i
      u.rated.i <- as.character(train[train$movieId==movie.id[i],]$userId)
      q.tilde[,i] <- solve(p.tilde[,u.rated.i] %*% t(p.tilde[,u.rated.i]) + lambda* diag(f+1)) %*%
        p.tilde[,u.rated.i] %*% (train[train$movieId==movie.id[i],]$rating - mu - bu[,u.rated.i])
    }
    
    # update bi and q
    bi[1,] <- q.tilde[1,]
    q <- q.tilde[-1,]
    
    
    # Rating Matrix
    mat <- matrix(rep(NA, U*I), ncol = I)
    for (u in 1:U) {
      for (i in 1:I) {
        mat[u, i] <- as.numeric(t(p[,u]) %*% q[,i])
      }
    }
    
    bu_ui <- matrix(rep(NA, U*I), ncol = I)
    for (i in 1:I) {
      bu_ui[,i] <- t(bu)
    }
    
    bi_ui <- matrix(rep(NA, U*I), ncol = I)
    for (u in 1:U) {
      bi_ui[u, ] <- bi
    }
    
    mu_ui <- matrix(rep(mu, U*I), ncol = I)
    
    R <- mu_ui + bu_ui + bi_ui + mat + bit_ui
    
    # Summerize
    cat("iter:", l, "\t")
    est_rating <- as.matrix(R) 
    colnames(est_rating) <- levels(as.factor(data$movieId))
    rownames(est_rating) <- levels(as.factor(data$userId))
    
    train_RMSE_cur <- RMSE(train, est_rating)
    cat("training RMSE:", train_RMSE_cur, "\t")
    train_RMSE <- c(train_RMSE, train_RMSE_cur)
    
    test_RMSE_cur <- RMSE(test, est_rating)
    cat("test RMSE:",test_RMSE_cur, "\n")
    test_RMSE <- c(test_RMSE, test_RMSE_cur)
 }
  
return(list(p = p, q = q, bi = bi, bu = bu, mu= mu, 
              train_RMSE = train_RMSE, test_RMSE = test_RMSE,
              est_rating = est_rating))
}
```
```{r}
result <- ALS.R3(f = 10, lambda = 5, max.iter = 5, data = data, train = data_train, test = data_test)
```


```{r}
save(ALS.R3, file = "../output/rmsea3r3.RData")
```

## KNN

```{r}
load("../output/rmsea3r3.Rdata")
rmse <- data.frame(rbind(t(result_summary[1,,]), t(result_summary[2,,])), train_test = rep(c("Train", "Test"), each = 4), par = rep(paste("f = ", f_l[,1], ", lambda = ", 10^f_l[,2]), times = 2)) %>% gather("epoch", "RMSE", -train_test, -par)
rmse$epoch <- as.numeric(gsub("X", "", rmse$epoch))
rmse %>% ggplot(aes(x = epoch, y = RMSE, col = train_test)) + geom_point() + facet_grid(~par)
```


#### Knn PostProcessing
```{r}
load("../output/mat_fac_r1r2new.RData")
library(lsa)
library(plyr)
ratingmean<-function(data){
  mean(data$rating)
}

rating<-ddply(data,.(movieId),ratingmean)
rating$index<-c(1:nrow(rating))


l_distance<-cosine(result$q)
diag(l_distance)<-0
cos_id<-rep(1:I,ncol=I)
knn_r<-rep(1:I,ncol=I)
for (i in 1:I){
    cos_id[i]<-which.max(rank(l_distance[,i]))
    knn_r[i]<-rating[rating$index==cos_id[i],]$V1
  }
```

#### Linear Regression for Training dataset
```{r}

data_train$movieindex<-dense_rank(data_train$movieId)

r<-rep(0,nrow(data_train))
for (i in 1:nrow(data_train)){
  rowindex<-data_train$userId[i]
  columindex<-data_train$movieindex[i]
  qi <- as.matrix(result$p[,rowindex])
  qj <- as.matrix(result$q[,columindex])
  r[i]<-t(qi)%*%qj
  }

```

```{r}
v<-rep(0,nrow(data_train))
for (i in 1:nrow(data_train)){
  rowindex<-data_train$userId[i]
  columindex<-data_train$movieindex[i]
  qi <- as.matrix(result$bu[rowindex])
  qj <- as.matrix(result$bi[columindex])
  v[i]<-qi+qj+result$mu
}

w<-knn_r[data_train$movieindex]
```

```{r}
data_train_linear<-as.data.frame(cbind(data_train$rating,r,v,w))
fit<-lm(V1~r+v+w,data=data_train_linear)
exp_rating<-predict(fit,data_train_linear)
(rmse_adj <- sqrt(mean((data_train_linear$V1 - exp_rating)^2)))
cat("The RMSE train of the adjusted model is", rmse_adj)
```

#### prediction
```{r}
data_test$movieindex<-dense_rank(data_test$movieId)

r1<-rep(0,nrow(data_test))
for (i in 1:nrow(data_test)){
  rowindex<-data_test$userId[i]
  columindex<-data_test$movieindex[i]
  qi <- as.matrix(result$p[,rowindex])
  qj <- as.matrix(result$q[,columindex])
  r1[i]<-t(qi)%*%qj
  }

```

```{r}
v1<-rep(0,nrow(data_test))
for (i in 1:nrow(data_test)){
  rowindex<-data_test$userId[i]
  columindex<-data_test$movieindex[i]
  qi <- as.matrix(result$bu[rowindex])
  qj <- as.matrix(result$bi[columindex])
  v1[i]<-qi+qj+result$mu
}

w1<-knn_r[data_test$movieindex]
```


```{r,warning=FALSE}
data_test_linear<-as.data.frame(cbind(data_test$rating,r1,v1,w1))
exp_rating_test<-predict(fit,data_test_linear)
rmse_adj_test <- sqrt(mean((data_test_linear$V1 - exp_rating_test)^2))
cat("The RMSE test of the adjusted model is", rmse_adj_test)
```

### Step 4 Evaluation
You should visualize training and testing RMSE by different dimension of factors and epochs ([One Epoch is when an ENTIRE dataset is passed forward and backward through the neural network only ONCE](https://towardsdatascience.com/epoch-vs-iterations-vs-batch-size-4dfb9c7ce9c9)). 

```{r}
library(ggplot2)

RMSE <- data.frame(epochs = seq(1, 4, 1), Training_MSE = result$train_RMSE, Test_MSE = result$test_RMSE) %>% gather(key = train_or_test, value = RMSE, -epochs)

RMSE %>% ggplot(aes(x = epochs, y = RMSE,col = train_or_test)) + geom_point() + scale_x_discrete(limits = seq(1, 5, 1)) + xlim(c(1, 4))+ylim(c(0,1))

```
